In [1]:
import numpy as np
# numpy를 np로 불러온다..?

In [2]:
# 1차원 예시
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [3]:
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [5]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
# 2차원 예시
# 배열 안에 배열..?
arr2 = np.array([[1,2,3],[5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

In [7]:
arr1

array([1, 2, 3, 4, 5])

In [8]:
# arr1 안에 원소가 5개 들어있다.
arr1.shape

(5,)

In [9]:
# 2 * 3 행렬로 되어 있다.
arr2.shape

(2, 3)

In [10]:
print(arr1)
print(arr1.size)
# size: 

[1 2 3 4 5]
5


In [11]:
# 배열의 타입 확인
print(arr1)
print(arr1.dtype)

[1 2 3 4 5]
int32


In [22]:
print(arr2)
print(arr2.dtype)
print(arr2.shape)

[[1 2 3]
 [5 6 7]]
int32
(2, 3)


In [14]:
# 배열의 차원(Dimension) 확인
print(arr1, arr1.ndim)
print(arr2, arr2.ndim)


[1 2 3 4 5] 1
[[1 2 3]
 [5 6 7]] 2


In [18]:
arr3 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [21]:
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)

3
(1, 4, 2)
8


In [31]:
arr4 = np.array([[[1,1,1],[1,2,3]],[[2,4,3],[2,3,4,]],[[4,5,6],[6,7,9]]])
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)

3
(3, 2, 3)
18


In [34]:
# 0이랑 1는 따로 숫자로 지정하지 않아도 들어간다. 실수형으로 들어간다.
# 정수로 넣고 싶으면 dtype으로 정수형으로 변환.
arr_zeros = np.zeros((3,4))
arr_zeros = np.ones((3,4))
arr_zeros

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
arr_full = np.full((5,5),7)
# 5행 5열에 7을 넣겠다.
arr_full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [44]:
list = []
for i in range(1,51):
    list.append(i)
print(list)
    # 오류 확인 하기..

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [45]:
arr = np.array(list)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [47]:
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [52]:
arr = np.arange(1, -50, -1)
arr

array([  1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11,
       -12, -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24,
       -25, -26, -27, -28, -29, -30, -31, -32, -33, -34, -35, -36, -37,
       -38, -39, -40, -41, -42, -43, -44, -45, -46, -47, -48, -49])

In [54]:
arr = np.random.rand(2,3)
# 랜덤값 배열 생성하기
arr

array([[0.58910168, 0.84495182, 0.84134364],
       [0.78281984, 0.07158255, 0.95689499]])

In [56]:
arr = np.random.randint(2,10)
# 2 이상 10 미만에서 랜덤으로 수 하나를 출력.
arr

4

In [57]:
arr = np.random.randint(2,10,size = (2,3))
# size = (2,3): 2행 3열로 출력
arr

array([[4, 3, 7],
       [6, 5, 6]])

In [59]:
arr_type = np.array([1.2,2.2,3.3], dtype = np.int64)
arr_type

array([1, 2, 3], dtype=int64)

In [60]:
arr_type = arr_type.astype("float64")
# float 으로 바꿀 때 "" 따옴표 꼭 붙히기.
arr_type

array([1., 2., 3.])

In [61]:
arr_type.dtype

dtype('float64')

In [62]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [63]:
arr + arr
# 1+1, 2+2, 3+3

array([2, 4, 6])

In [64]:
arr * arr
# 1*1, 2*2, 3*3

array([1, 4, 9])

In [65]:
arr_a = np.array([1,2,3])
arr_a

array([1, 2, 3])

In [66]:
arr_b = np.array([4,3,2])
arr_b

array([4, 3, 2])

In [72]:
arr_a + arr_b

array([5, 5, 5])

In [73]:
arr_a - arr_b

array([-3, -1,  1])

In [74]:
arr_a * arr_b

array([4, 6, 6])

In [75]:
arr_a / arr_b

array([0.25      , 0.66666667, 1.5       ])

In [76]:
arr2_a = np.array([[1,2,3],[3,4,5]])
arr2_a 

array([[1, 2, 3],
       [3, 4, 5]])

In [77]:
arr2_b = np.array([[1,2,2],[1,1,1]])
arr2_b 

array([[1, 2, 2],
       [1, 1, 1]])

In [78]:
arr2_a + arr2_b

array([[2, 4, 5],
       [4, 5, 6]])

In [79]:
# list와 단일 정수와 연산 가능...

arr2_a + 3 

array([[4, 5, 6],
       [6, 7, 8]])

In [80]:
arr2_b * 4

array([[4, 8, 8],
       [4, 4, 4]])

In [81]:
arr_1 = np.array([1,2,3,4,0])
arr_1

array([1, 2, 3, 4, 0])

In [82]:
arr_1[1]

2

In [87]:
arr = np.array([[1,2,3],[8,1,1]])
arr

array([[1, 2, 3],
       [8, 1, 1]])

In [84]:
arr[0]

array([1, 2, 3])

In [88]:
arr[1][0]
# list의 중첩!!! 첫 번쨰 리스트에서 첫 번쨰 자리수 출력

8

In [90]:
arr[1,0]

8

In [95]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
# slicing
# 3이상 8미만
arr1[3:4]

array([11])

In [102]:
arr1[3:5] = 11
arr1

array([ 1,  2,  3, 11, 11, 11, 11, 11,  9, 10])

In [104]:
arr2 = np.arange(50).reshape(5,10)
# 2차원 안에 10개씩, 1차원 안에 5 줄...?
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [107]:
arr2[:2,:]
# 0행 부터 1행까지, 전체 열 출력

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [109]:
arr2[:,0]
# 행은 다 뽑아줄게, 그리고 열은 첫 번쨰 열만 뽑아 줄게

array([ 0, 10, 20, 30, 40])

In [110]:
arr2[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [115]:
arr2[0,4]

4

In [120]:
score = np.array([80,70,60,90])
score

array([80, 70, 60, 90])

In [121]:
score <= 80

array([ True,  True,  True, False])

In [122]:
score[score >= 80]
# 인덱싱이니까 [] 대괄호를 친다.

array([80, 90])

In [123]:
name = np.array(["same", "tom", "rora", "kim"])
name

array(['same', 'tom', 'rora', 'kim'], dtype='<U4')

In [125]:
bool = np.array([False, True, False, True])
bool

array([False,  True, False,  True])

In [126]:
name[bool]
# boolean은 True인 값만 반환하기 때문에 False값은 출력하지 않는다.

array(['tom', 'kim'], dtype='<U4')

In [129]:
score = np.array([[60,60],[70,70],[80,80],[90,90]])
print(score)
print(score.ndim)

[[60 60]
 [70 70]
 [80 80]
 [90 90]]
2


In [130]:
name == "bob"

array([False, False, False, False])

In [131]:
name == "tom"

array([False,  True, False, False])

In [133]:
score[name == "same"]

array([[60, 60]])

In [135]:
arr = np.random.randint(1,10, size = (2,5))
# 따로 지정하지 않으면 int 하나만 출력하는데 size = (2,5)를 써서 원하는 만큼 출력
arr

array([[9, 3, 3, 5, 5],
       [8, 1, 2, 6, 2]])

In [145]:
print(arr.sum())
print(np.sum(arr))

57
57


In [141]:
arr = np.random.randint(1,10,size = (2,5))
arr

array([[9, 8, 4, 7, 7],
       [4, 3, 7, 1, 7]])

In [144]:
print(arr.mean())
print(np.mean(arr))

5.7
5.7


In [147]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [148]:
np.sqrt(arr)
# sqrt = 제곱근

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [151]:
arr = np.array([1,-1,2,-3,5])
arr

array([ 1, -1,  2, -3,  5])

In [152]:
np.abs(arr)
# 절대값

array([1, 1, 2, 3, 5])

### numpy는 왜 쓰는 것? 언제 사용?
- 수치 데이터를 활용하기 좋은 무언가...

## 실습

In [156]:
import numpy as np

In [162]:
arr_student = (["a", "b", "c"])
arr_score = np.array([[10, 70], [20, 80], [30, 100]])
mid_score = arr_score[:,0]
final_score = arr_score[:,1]
total_score = mid_score + final_score
sentence = f"이름: {arr_student}, 성적: {total_score}원 입니다."
print(mid_score)
print(final_score)
print(total_score)
print(sentence)

[10 20 30]
[ 70  80 100]
[ 80 100 130]
이름: ['a', 'b', 'c'], 성적: [ 80 100 130]원 입니다.


In [157]:
mid_score = np.array([10,20,30])
final_score = np.array([70,80,100])
total = mid_score + final_score
total

array([ 80, 100, 130])

### 실습1
- 0에서 9까지 정수 값을 가지는 ndarray 객체 array_a를 넘파이를 이용해 출력

In [165]:
array_a = [0,1,2,3,4,5,6,7,8,9]
array_a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### 실습2
- range[]함수를 사용해 0에서 9까지 정스 값 가지는 array_b 출력

In [169]:
array_b = np.arange(0,10)
array_b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 실습3
- 0에서 9까지의 정수 값에서 짝수를 가지는 array_c

In [170]:
array_c = np.arange(0,10, 2)
# 2의 간격으로 0부터 출력
array_c


array([0, 2, 4, 6, 8])

### 실습4
- array_c의 shape, ndim, size

In [172]:
print(array_c.shape)
print(array_c.ndim)
print(array_c.size)
print(array_c.dtype)

(5,)
1
5
int32


### 실습5
- 회사의 매출이 올라서 전 직원의 월급을 100만원씩 올려줌
- 현재 직원의 월급: 200, 250, 300, 350, 400

In [174]:
# 회사의 매출이 올라서 전 직원의 월급을 100만원씨가 올려줌
# 현재 직원의ㅏ 월급: 200, 250, 300, 350, 400

salary = np.array([200, 250, 300, 350, 400])
increase_salary = salary + 100
increase_salary

array([300, 350, 400, 450, 500])

In [175]:
salary = np.array([200, 250, 300, 350, 400])
increase_salary = salary * 2
increase_salary

array([400, 500, 600, 700, 800])

In [178]:
matrix_array2 = np.array([[1,2,3],[1,1,1],[0,0,0],[7,8,9]])
matrix_array3 = np.array([[[1,1],[2,1]],[[3,3],[0,9]]])
print(matrix_array2.ndim, matrix_array3.ndim)
print(matrix_array2.shape, matrix_array3.shape)
print(matrix_array2.size, matrix_array3.size)

2 3
(4, 3) (2, 2, 2)
12 8


In [189]:
# 선수 중 몸무게 80 이상
# 선수 중 키가 180 이상만 출력

players = np.array([[170, 76.4], [183.4,78.5], [190.1, 80.3], [187.2, 81]])
players

array([[170. ,  76.4],
       [183.4,  78.5],
       [190.1,  80.3],
       [187.2,  81. ]])

In [192]:
players_weight = players[:,1]
print(players_weight[players_weight >= 80.0])

[80.3 81. ]


In [228]:
players_weight = players[:,1:]
# , 콤마를 기준으로 행이냐 열이냐
print(players_weight[players_weight >= 80.0])

[80.3 81. ]


In [195]:
print(players[players[:,1] >= 80.0])

[[190.1  80.3]
 [187.2  81. ]]


In [193]:
players_height = players[:,0]
print(players_height[players_height >= 180.0])

[183.4 190.1 187.2]


In [196]:
print(players[players[:,0] >= 180.0])

[[183.4  78.5]
 [190.1  80.3]
 [187.2  81. ]]


In [208]:
revenue_in_yen = np.array([300000, 400000, 3400000, 140000, 180000, 200000, 100000, 300000,
                           100000, 340000, 330000, 320000, 350000, 360000, 400000, 420000, 
                           200000,320000, 320000, 330000, 340000, 360000, 330000, 320000,
                           310000, 300000, 340000])
                  
print(revenue_in_yen)
print(revenue_in_yen.ndim)

[ 300000  400000 3400000  140000  180000  200000  100000  300000  100000
  340000  330000  320000  350000  360000  400000  420000  200000  320000
  320000  330000  340000  360000  330000  320000  310000  300000  340000]
1


In [206]:
won_array = revenue_in_yen * 9.77
won_array

array([ 2931000.,  3908000., 33218000.,  1367800.,  1758600.,  1954000.,
         977000.,  2931000.,   977000.,  3321800.,  3224100.,  3126400.,
        3419500.,  3517200.,  3908000.,  4103400.,  1954000.,  3126400.,
        3126400.,  3224100.,  3321800.,  3517200.,  3224100.,  3126400.,
        3028700.,  2931000.,  3321800.])

In [219]:
dallar_array = np.array([2000, 2200, 2300, 2400, 1500, 1600, 2800, 2700, 
                        2300, 2400, 2500, 2200, 2100, 2600, 2700, 2200, 
                        2500, 2600, 2700, 2000, 3000, 3200, 3300, 3400,
                        2300, 2500, 2300])
dallar_array

array([2000, 2200, 2300, 2400, 1500, 1600, 2800, 2700, 2300, 2400, 2500,
       2200, 2100, 2600, 2700, 2200, 2500, 2600, 2700, 2000, 3000, 3200,
       3300, 3400, 2300, 2500, 2300])

In [220]:
won_array2 = dallar_array * 1301
won_array2

array([2602000, 2862200, 2992300, 3122400, 1951500, 2081600, 3642800,
       3512700, 2992300, 3122400, 3252500, 2862200, 2732100, 3382600,
       3512700, 2862200, 3252500, 3382600, 3512700, 2602000, 3903000,
       4163200, 4293300, 4423400, 2992300, 3252500, 2992300])

In [221]:
total_array = won_array + won_array2
total_array

array([ 5533000.,  6770200., 36210300.,  4490200.,  3710100.,  4035600.,
        4619800.,  6443700.,  3969300.,  6444200.,  6476600.,  5988600.,
        6151600.,  6899800.,  7420700.,  6965600.,  5206500.,  6509000.,
        6639100.,  5826100.,  7224800.,  7680400.,  7517400.,  7549800.,
        6021000.,  6183500.,  6314100.])

In [225]:
print(won_array[won_array <= 2000000])
print(won_array2[won_array2 <= 2000000])
print(total_array[total_array <= 4000000])

[1367800. 1758600. 1954000.  977000.  977000. 1954000.]
[1951500]
[3710100. 3969300.]


In [229]:
array1 = np.array([11,22,33,44,55,12,13])
array1

array([11, 22, 33, 44, 55, 12, 13])

In [236]:
print(array1.median())
# ?? 질문!!!!!!!

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [231]:
# 최댓값 max
# 최솟값 min
print(array1.max())
print(array1.min())

55
11


In [235]:
# 중앙값: median
# 표준편차: std
# 분산: var
print(np.median(array1))
print(array1.std())
print(array1.var())

22.0
16.08396336575722
258.69387755102036
